backend:
  name: git-gateway
  branch: master
media_folder: src/assets/images
public_folder: assets/images
collections:
  - name: pages
    label: Sider
    files:
      - label: Velkommen
        name: index
        file: src/content/sections/index.md
        fields:
          - { label: Velkommen, name: body, widget: markdown, editor_components: [] }
          - label: Billeder
            name: images
            widget: list
            summary: '{{fields.image}}'
            minimize_collapsed: true
            fields:
            - { name: image, label: Billede, widget: image, choose_url: false, allow_multiple: false }
      - label: Faciliteter
        name: facilities
        file: src/content/sections/facilities.md
        fields:
          - { label: Faciliteter, name: body, widget: markdown, editor_components: [] }
          - label: Billeder
            name: images
            widget: list
            summary: '{{fields.image}}'
            minimize_collapsed: true
            fields:
            - { name: image, label: Billede, widget: image, choose_url: false, allow_multiple: false }
      - label: Regler
        name: rules
        file: src/content/sections/rules.md
        fields:
          - { label: Regler, name: body, widget: markdown, editor_components: [] }
      - label: Priser
        name: prices
        file: src/content/sections/prices.md
        fields:
          - { label: Priser, name: body, widget: markdown, editor_components: [] }
      - label: Om os
        name: about
        file: src/content/sections/about.md
        fields:
          - { label: Om os, name: body, widget: markdown, editor_components: [] }
          - { label: Lokation, name: map, widget: map }
