backend:
  name: git-gateway
  branch: master
media_folder: src/assets/images
public_folder: assets/images
collections:
  - name: pages
    label: Sider
    files:
      - label: Hovedside
        name: index
        file: src/content/index.md
        fields:
          - { label: Titel, name: title, widget: string, default: Mosevang Ridecenter }
          - { label: Velkommen, name: body, widget: markdown, editor_components: [] }
          - { label: Første billeder, name: primary_images, widget: image, choose_url: false }
          - { label: Faciliteter, name: facilities, widget: markdown }
          - { label: Facilitet billeder, name: facilities_images, wiget: image, choose_url: false }
          - { label: Regler, name: rules, widget: markdown, editor_components: [] }
          - { label: Priser, name: prices, widget: markdown, editor_components: [] }
          - { label: Om os, name: about, widget: markdown, editor_components: [] }
          - { label: Lokation, name: map, widget: map }
